### ISSUE TITLE
Exoplayer crashes on init on Android 5.1

### ISSUE THREAD

**Issue by bemnet4u** [martijn00/ExoPlayerXamarin#39]
Starting Exoplayer on Android 5.1 causes a crash like this. 

I am starting the player like this. I can repro the crash both on emulator and device.
```
mainHandler = new Handler();
bandwidthMeter = new DefaultBandwidthMeter();
FixedTrackSelection.Factory trackSelection =
	                   new FixedTrackSelection.Factory();
TrackSelector trackSelector =
                         new DefaultTrackSelector(mainHandler, trackSelection);

// 2. Create a default LoadControl
DefaultLoadControl loadControl = new DefaultLoadControl();
// 3. Create the player
mediaPlayer =
ExoPlayerFactory.NewSimpleInstance(Forms.Context, trackSelector, loadControl);

```

```
System.NotSupportedException: Could not activate JNI Handle 0x41245338 (key_handle 0x41245338) of Java type 'md5f170bbb6b61c93fc18e3a047e02d52b2/MediaPlayerService' as managed type 'AndroidSharedRadioLibrary.MediaPlayerService'. ---> Java.Lang.LinkageError: com/google/android/exoplayer2/mediacodec/MediaCodecRenderer
  at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw () [0x0000c] in <ecf4a1a627f545d793bb611dec828a4b>:0
  at Java.Interop.JniEnvironment+StaticMethods.CallStaticObjectMethod (Java.Interop.JniObjectReference type, Java.Interop.JniMethodInfo method, Java.Interop.JniArgumentValue* args) [0x00082] in <416acbd7c0374f16924e03eb9254e276>:0
  at Android.Runtime.JNIEnv.CallStaticObjectMethod (System.IntPtr jclass, System.IntPtr jmethod, Android.Runtime.JValue* parms) [0x0000e] in <1b9025bec4f543eba09722bb3dcb8e68>:0
  at Com.Google.Android.Exoplayer2.ExoPlayerFactory.NewSimpleInstance (Android.Content.Context p0, Com.Google.Android.Exoplayer2.Trackselection.TrackSelector p1, Com.Google.Android.Exoplayer2.ILoadControl p2) [0x00079] in /Users/bmerha/RadioApp_TFS/RadioApp/ExoPlayer/obj/Debug/generated/src/Com.Google.Android.Exoplayer2.ExoPlayerFactory.cs:89
  at SharedRadioLibrary.Droid2.ExoMediaPlayer..ctor () [0x0003e] in /Users/bmerha/RadioApp_TFS/RadioApp/SharedRadioLibrary.Droid2/DependencyServices/ExoMediaPlayer.cs:37
  at AndroidSharedRadioLibrary.MediaPlayerService..ctor () [0x00020] in /Users/bmerha/RadioApp_TFS/RadioApp/SharedRadioLibrary.Droid2/DependencyServices/MediaPlayerService.cs:70
  at at (wrapper dynamic-method) System.Object:01bcd123-a28b-4c94-b507-2a6188b21c16 (intptr,object[])
  at Java.Interop.TypeManager.n_Activate (System.IntPtr jnienv, System.IntPtr jclass, System.IntPtr typename_ptr, System.IntPtr signature_ptr, System.IntPtr jobject, System.IntPtr parameters_ptr) [0x000fb] in <1b9025bec4f543eba09722bb3dcb8e68>:0
  at java.lang.VerifyError: com/google/android/exoplayer2/mediacodec/MediaCodecRenderer
  at at com.google.android.exoplayer2.SimpleExoPlayer.buildRenderers(SimpleExoPlayer.java:535)
  at at com.google.android.exoplayer2.SimpleExoPlayer.<init>(SimpleExoPlayer.java:138)
  at at com.google.android.exoplayer2.ExoPlayerFactory.newSimpleInstance(ExoPlayerFactory.java:103)
  at at com.google.android.exoplayer2.ExoPlayerFactory.newSimpleInstance(ExoPlayerFactory.java:81)
  at at com.google.android.exoplayer2.ExoPlayerFactory.newSimpleInstance(ExoPlayerFactory.java:62)
  at at com.google.android.exoplayer2.ExoPlayerFactory.newSimpleInstance(ExoPlayerFactory.java:47)
  at at mono.android.TypeManager.n_activate(Native Method)
  at at mono.android.TypeManager.Activate(TypeManager.java:7)
  at at md5f170bbb6b61c93fc18e3a047e02d52b2.MediaPlayerService.<init>(MediaPlayerService.java:29)
  at at java.lang.Class.newInstanceImpl(Native Method)
  at at java.lang.Class.newInstance(Class.java:1319)
  at at android.app.ActivityThread.handleCreateService(ActivityThread.java:2234)
  at at android.app.ActivityThread.access$1600(ActivityThread.java:123)
  at at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1201)
  at at android.os.Handler.dispatchMessage(Handler.java:99)
  at at android.os.Looper.loop(Looper.java:137)
  at at android.app.ActivityThread.main(ActivityThread.java:4424)
  at at java.lang.reflect.Method.invokeNative(Native Method)
  at at java.lang.reflect.Method.invoke(Method.java:511)
  at at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:784)
  at at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:551)
  at at dalvik.system.NativeStart.main(Native Method)
  --- End of inner exception stack trace ---
  at Java.Interop.TypeManager.n_Activate (System.IntPtr jnienv, System.IntPtr jclass, System.IntPtr typename_ptr, System.IntPtr signature_ptr, System.IntPtr jobject, System.IntPtr parameters_ptr) [0x00189] in <1b9025bec4f543eba09722bb3dcb8e68>:0
  at at (wrapper dynamic-method) System.Object:de7db137-f1a7-49f5-a436-ba77c7827a19 (intptr,intptr,intptr,intptr,intptr,intptr)

```

**Comment by bemnet4u** [comment]
I think I was having issue because I was initializing the player early. I was creating it in my media service constractor. I see in your examples you create it when you start playing.

I am now going to try to use your other api the MediaManager...looks like i am able to use ExoPlayer though the media manager.
